name: googleauth
description: A new Flutter project.

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.4.1
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  google_fonts:
  form_field_validator: ^1.1.0
  pie_chart: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/